### ISSUE TITLE
'unable to parse the mail file'

### ISSUE THREAD

**Issue by mjbeggs** [pulsovi/obsidian_eml_reader#1]
I just installed version 1.1.0 of Email Reader in my Obsidian vault and added a link to an mjbeggs02@gmail.com file saved in the vault folder. When I switch to preview the header of the email is shown along with the text 'unable to parse the mail file'. 
Clicking on the Obsidian link opens the mjbeggs02@gmail.com fil ein my email client which doesn't show any issues. The email is only text (no attachements).
Is there something up with the email, or am I missing something on how to use Email Reader

**Comment by pulsovi** [comment]
Hi,

I'm sorry to hear that you are having a problem with this plugin.

I'm guessing that the content of an email is often confidential. But I'm going to have a hard time helping without a complete example with the `.md` file and the `.eml` file.

Can you at least tell me what procedure you followed to obtain the email file?

**Comment by mjbeggs** [comment]
David,

I selected the "Save as/File..." command in my email client Postbox (version 7.0.6) to create the eml file.
I have attached both the eml and the md files.

Mike

David GABISON wrote on 11/16/23 5:09 AM:

**Comment by pulsovi** [comment]
Thank you very much for your feedback,

Thanks to you, I was able to identify the problem and resolve it — text-only emails were not handled correctly.

A new corrected version of the plugin is available on Obsidian.

**Comment by mjbeggs** [comment]
David,

It works great!
Thank you.

Mike

David GABISON wrote on 11/19/23 1:45 PM:
