### ISSUE TITLE
Difference to MSG Handler?

### ISSUE THREAD

**Issue by jbirnick** [pulsovi/obsidian_eml_reader#2]
There is also this plugin:

https://github.com/ozntel/obsidian-msg-handler

What are the differences? Is there anything your plugin can do which the one above can not do?

**Comment by pulsovi** [comment]
Hi,

Thank you for your message.

I didn't know about this plugin.
However, I searched hard before deciding to write one myself.

I like open source, it generally avoids unnecessary duplication. This was the reason for this README.

To answer your question, obviously the plugin you cite does not less but more than mine.

I will therefore stop developing and maintaining here and contribute to `obsidian-msg-handler` as best I can.
